live_config_reload = true

[colors.bright]
black = "0x636363"
blue = "0x7eaac7"
cyan = "0x86d3ce"
green = "0x909d63"
magenta = "0xaa6292"
red = "0xbc5653"
white = "0xf7f7f7"
yellow = "0xebc17a"

[colors.cursor]
cursor = "0xd9d9d9"
text = "0x2c2c2c"

[colors.dim]
black = "0x232323"
blue = "0x556b79"
cyan = "0x5c8482"
green = "0x5e6547"
magenta = "0x6e4962"
red = "0x74423f"
white = "0x828282"
yellow = "0x8b7653"

[colors]
draw_bold_text_with_bright_colors = true

[colors.normal]
black = "0x1c1c1c"
blue = "0x7eaac7"
cyan = "0x86d3ce"
green = "0x909d63"
magenta = "0xaa6292"
red = "0xbc5653"
white = "0xcacaca"
yellow = "0xebc17a"

[colors.primary]
background = "0x111111"
# bright_background = "0x3a3a3a"
bright_foreground = "0xd9d9d9"
# dim_background = "0x202020"
dim_foreground = "0xdbdbdb"
foreground = "0xF4F4FF"

[env]
TERM = "xterm-256color"

[font]
size = 14.0

[font.bold]
#family = "BlexMono NFM"
#family = "CaskaydiaMono Nerd Font Mono"
family = "Inconsolata LGC Nerd Font Mono"
style = "Bold"

[font.italic]
#family = "BlexMono NFM"
#family = "CaskaydiaMono Nerd Font Mono"
family = "Inconsolata LGC Nerd Font Mono"
style = "Italic"

[font.normal]
#family = "BlexMono NFM"
#family = "CaskaydiaMono Nerd Font Mono"
family = "Inconsolata LGC Nerd Font Mono"
style = "Regular"

[keyboard]
bindings = [ 
# ** `\u0002` = CTRL + B (TMUX Prefix)
# Rename the current tmux window name, `cmd + ,`
{ key = "Comma", mods = "Command", chars = "\u0002,"}, 
# Select a new tmux session for the attached client interactively, `cmd + k`
{ key = "K", mods = "Command", chars = "\u0002s" },
# Select tmux window 1-5, `cmd + 1`
{ key = "Key1", mods = "Command", chars = "\u00021" }, 
# Select tmux window 1-5, `cmd + 2`
{ key = "Key2", mods = "Command", chars = "\u00022" },
# Select tmux window 1-5, `cmd + 3`
{ key = "Key3", mods = "Command", chars = "\u00023" },
# Select tmux window 1-5, `cmd + 4`
{ key = "Key4", mods = "Command", chars = "\u00024" },
# Select tmux window 1-5, `cmd + 5`
{ key = "Key5", mods = "Command", chars = "\u00025" },
# Popup and switch tmux pane, `cmd + j`
{ key = "J", mods = "Command", chars = "\u0002\f" }, 
# Change to the previous tmux window, `cmd + shift + j`
{ key = "J", mods = "Command|Shift", chars = "\u0002p" }, 
# Change to the next tmux window, `cmd + shift + k`
{ key = "K", mods = "Command|Shift", chars = "\u0002n" }, 
# Detach the current tmux client, `cmd + shift + d`
{ key = "D", mods = "Command|Shift", chars = "\u0002d" },
# Create a new tmux window, `cmd + t`
{ key = "T", mods = "Command", chars = "\u0002c" }, 
# Break the current tmux pane out of the tmux window, `cmd + shift + t`
{ key = "T", mods = "Command|Shift", chars = "\u0002!" }, 
# Kill the current tmux pane (and window if last pane), `cmd + x`
{ key = "X", mods = "Command", chars = "\u0002x" }, 
# Toggle the zoom state of the current tmux pane, `cmd + z`
{ key = "Z", mods = "Command", chars = "\u0002z" },
# Enter Tmux Copy mode, `cmd + alt + [`
{ key = "LBracket", mods = "Command|Alt", chars = "\u0002[" }, 
# Type <escape>:w<enter> to save vim/neovim, `cmd + s`
{ key = "S", mods = "Command", chars = "\u001B:w\n" },
# open file, `cmd + f`
{ key = "F", mods = "Command", chars = "fto\n" }, 
# cd into the directory of the selected file, `cmd + g`
{ key = "G", mods = "Command", chars = "cdft\n" }, 
# Change working dir in shell to last dir in lf, `cmd + l`
{ key = "L", mods = "Command", chars = "lfcd\n" } 
]

[mouse]
hide_when_typing = false

[scrolling]
history = 10000
multiplier = 3

[selection]
save_to_clipboard = true
semantic_escape_chars = ",│`|:\"' ()[]{}<>\t"

#[terminal.shell]
[shell]
program = "/bin/zsh"
args = ["-l", "-c", "if tmux has-session 2>/dev/null; then tmux attach; else tmux new -s lab; fi"]

[window]
decorations = "Buttonless"
opacity = 0.78
blur = true
startup_mode = "Maximized"
padding = { x = 5, y = 3}
option_as_alt = "Both"

#[general]
#live_config_reload = true

[terminal]

#[window.padding]
#x = 3
#y = 3
